# Generated by Django 4.2.16 on 2024-10-20 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categorys",
            new_name="Category",
        ),
    ]
